cancer_detection/cancer_detection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predict_cancer.urls', namespace = 'predict'))
]

cancer_detection/predict_cancer/urls.py
from django.urls import path
from . import views

app_name = 'predict'

urlpatterns = [
    path('', views.predict, name = 'prediction_page'),
    path('predict/', views.predict_chances, name = 'submit_prediction'),
    path('results/', views.view_results, name = 'results'),
]

cancer_detection/predict_cancer/models.py
from django.db import models

class PredResults(models.Model):
	mean_radius = models.FloatField()
	mean_texture = models.FloatField()
	mean_perimeter = models.FloatField()
	mean_area = models.FloatField()
	mean_smoothness = models.FloatField()
	classification = models.CharField(max_length=30)

	def __str__(self):
		return self.classification

cancer_detection/predict_cancer/views.py
from django.shortcuts import render
from django.http import JsonResponse
import pandas as pd
from .models import PredResults

def predict(request):
	return render(request, 'predict.html')

def predict_chances(request):
	if request.POST.get('action') == 'post':
		mean_radius = float(request.POST.get('mean_radius'))
		mean_texture = float(request.POST.get('mean_texture'))
		mean_perimeter = float(request.POST.get('mean_perimeter'))
		mean_area = float(request.POST.get('mean_area'))
		mean_smoothness = float(request.POST.get('mean_smoothness'))

		# Unpickle the model
		model = pd.read_pickle(r"D:\\Python\\cancer_detection\\new_model.pickle")
		result = model.predict([[mean_radius, mean_texture, mean_perimeter, mean_area, mean_smoothness]])

		classification = result[0]

		PredResults.objects.create(mean_radius = mean_radius, mean_texture = mean_texture, mean_perimeter = mean_perimeter,
		 mean_area = mean_area, mean_smoothness = mean_smoothness, classification = classification)

		return JsonResponse({ 'result' : classification, 'mean_radius' : mean_radius, 'mean_texture' : mean_texture, 
			'mean_perimeter' : mean_perimeter, 'mean_area' : mean_area, 'mean_smoothness' : mean_smoothness}, safe = False)

def view_results(request):
	data = { "dataset" : PredResults.objects.all() }
	return render(request, "results.html", data)

cancer_detection/templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Cancer prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

cancer_detection/templates/predict.html
{% extends "base.html" %}

{% block main %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Mean Radius: <span id="mr"></span></div>
                <div>Mean Texture: <span id="mt"></span></div>
                <div>Mean Perimeter: <span id="mp"></span></div>
                <div>Mean Area: <span id="ma"></span></div>
                <div>Mean Smoothness: <span id="ms"></span></div>
                <h5 class="pt-3">Prediction Classification:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results" role="button">View DB</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Cancer Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="mean_radius">Mean Radius</label>
                    <input type="number" step="any" class="form-control" id="mean_radius" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="mean_texture">Mean Texture</label>
                    <input type="number" step="any" class="form-control" id="mean_texture" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="mean_perimeter">Mean Perimeter</label>
                    <input type="number" step="any" class="form-control" id="mean_perimeter" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="mean_area">Mean Area</label>
                    <input type="number" step="any" class="form-control" id="mean_area" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="mean_smoothness">Mean Smoothness</label>
                    <input type="number" step="any" class="form-control" id="mean_smoothness" placeholder="" required>
                </div>
                <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "predict:submit_prediction" %}',
            data:{
                mean_radius:$('#mean_radius').val(),
                mean_texture:$('#mean_texture').val(),
                mean_perimeter:$('#mean_perimeter').val(),
                mean_area:$('#mean_area').val(),
                mean_smoothness:$('#mean_smoothness').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("mr").innerHTML = json['mean_radius']
                document.getElementById("mt").innerHTML = json['mean_texture']
                document.getElementById("mp").innerHTML = json['mean_perimeter']
                document.getElementById("ma").innerHTML = json['mean_area']
                document.getElementById("ms").innerHTML = json['mean_smoothness']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

cancer_detection/templates/results.html
{% extends "base.html" %}

{% block main %}
    <div class="container pt-5">
        <div class="row">

        <h1>Prediction Results</h1>

            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Mean Radius</th>
                <th scope="col">Mean Texture</th>
                <th scope="col">Mean Perimeter</th>
                <th scope="col">Mean Area</th>
                <th scope="col">Mean Smoothness</th>
                <th scope="col">Prediction</th>
                </tr>
                </thead>
                <tbody>
                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.mean_radius }}</td>
                    <td>{{ data.mean_texture }}</td>
                    <td>{{ data.mean_perimeter }}</td>
                    <td>{{ data.mean_area }}</td>
                    <td>{{ data.mean_smoothness }}</td>
                    <td>{{ data.classification }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}